version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"  # Expose le port MongoDB
    volumes:
      - mongo-data:/data/db  # Persiste les données de MongoDB
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
