
spring.application.name=user-service

# Connexion à la base de données PostgreSQL
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/userdb}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:adminuser}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.default_schema=users
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.locations=classpath:db/migration/
spring.flyway.enabled=true


# Swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true

# Server Configuration
server.port=${PORT:8084}