--
-- PostgreSQL database dump
--



-- Dumped from database version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: abonnements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.abonnements (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    lecteur_id uuid NOT NULL,
    categorie_id uuid NOT NULL,
    status character varying(50) DEFAULT 'ACTIF'::character varying NOT NULL,
    subscribed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    unsubscribed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.abonnements OWNER TO postgres;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    domain character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: lecteurs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lecteurs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'PENDING'::character varying NOT NULL,
    user_type character varying(50) DEFAULT 'LECTEUR'::character varying NOT NULL,
    preferences text,
    newsletter_active boolean DEFAULT true,
    notification_email boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.lecteurs OWNER TO postgres;

--
-- Name: redacteurs; Type: TABLE; Schema: public; Owner: postgres

--

CREATE TABLE public.newsletters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255),
    content text,
    author_email character varying(255) NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    published_at timestamp without time zone
);

ALTER TABLE public.newsletters OWNER TO postgres;
CREATE TABLE public.redacteurs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'PENDING'::character varying NOT NULL,
    user_type character varying(50) DEFAULT 'REDACTEUR'::character varying NOT NULL,
    bio text,
    specialite character varying(100),
    nombre_articles integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.redacteurs OWNER TO postgres;
CREATE TABLE public.consumer_groups (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    group_id character varying(255) NOT NULL,
    category_signature text NOT NULL,
    topics_subscribed text NOT NULL,
    reader_count integer DEFAULT 0 NOT NULL,
    status character varying(50) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_consumed_at timestamp without time zone
);

ALTER TABLE public.consumer_groups OWNER TO postgres;

--
-- Name: abonnements abonnements_lecteur_id_categorie_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.abonnements
    ADD CONSTRAINT abonnements_lecteur_id_categorie_id_key UNIQUE (lecteur_id, categorie_id);


--
-- Name: abonnements abonnements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.abonnements
    ADD CONSTRAINT abonnements_pkey PRIMARY KEY (id);


--
-- Name: categories categories_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_name_key UNIQUE (name);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: lecteurs lecteurs_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lecteurs
    ADD CONSTRAINT lecteurs_email_key UNIQUE (email);


--
-- Name: lecteurs lecteurs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lecteurs
    ADD CONSTRAINT lecteurs_pkey PRIMARY KEY (id);


--
-- Name: redacteurs redacteurs_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.redacteurs
    ADD CONSTRAINT redacteurs_email_key UNIQUE (email);


--
-- Name: redacteurs redacteurs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.redacteurs
    ADD CONSTRAINT redacteurs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.consumer_groups
    ADD CONSTRAINT consumer_groups_pkey PRIMARY KEY (id);

--
-- Name: consumer_groups consumer_groups_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consumer_groups
    ADD CONSTRAINT consumer_groups_group_id_key UNIQUE (group_id);    


ALTER TABLE ONLY public.newsletters
    ADD CONSTRAINT newsletters_pkey PRIMARY KEY (id);
--
-- Name: idx_abonnements_categorie; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_abonnements_categorie ON public.abonnements USING btree (categorie_id);


--
-- Name: idx_abonnements_lecteur; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_abonnements_lecteur ON public.abonnements USING btree (lecteur_id);


--
-- Name: idx_abonnements_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_abonnements_status ON public.abonnements USING btree (status);


--
-- Name: idx_lecteurs_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_lecteurs_email ON public.lecteurs USING btree (email);


--
-- Name: idx_lecteurs_newsletter; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_lecteurs_newsletter ON public.lecteurs USING btree (newsletter_active);


--
-- Name: idx_lecteurs_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_lecteurs_status ON public.lecteurs USING btree (status);


--
-- Name: idx_redacteurs_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_redacteurs_email ON public.redacteurs USING btree (email);

cREATE INDEX idx_newsletters_status ON public.newsletters USING btree (status);

--
-- Name: idx_newsletters_author_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_newsletters_author_email ON public.newsletters USING btree (author_email);



--
-- Name: idx_redacteurs_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_redacteurs_status ON public.redacteurs USING btree (status);

CREATE INDEX idx_consumer_groups_status ON public.consumer_groups USING btree (status);

--
-- Name: abonnements abonnements_categorie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.abonnements
    ADD CONSTRAINT abonnements_categorie_id_fkey FOREIGN KEY (categorie_id) REFERENCES public.categories(id) ON DELETE CASCADE;


--
-- Name: abonnements abonnements_lecteur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.abonnements
    ADD CONSTRAINT abonnements_lecteur_id_fkey FOREIGN KEY (lecteur_id) REFERENCES public.lecteurs(id) ON DELETE CASCADE;



